import Head from 'next/head';
import Navbar from '../components/Navbar/Navbar';
import About from '../components/About/About';

export default function Home() {
  return (
    <>
      <Head>
        <title>&lt;Suvorov /&gt; | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <About />
    </>
  );
}
